name: Build and Deploy to Cloud Run

on:
  push:
    branches: ["dev"]

env:
  PROJECT_ID: speedy-elf-396105
  GAR_LOCATION: us-central1
  REPO_NAME: dexters-lab
  CR_SERVICE: ip-location-mapper-dev
  REGION: us-central1

jobs:
  config:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 363.0.0"
          project_id: ${{ env.PROJECT_ID }}

  build:
    needs: config
    steps:
      - name: Authenticate Docker with gcloud
        run: |
          echo "$(gcloud auth print-access-token)" | docker login -u oauth2accesstoken \
            --password-stdin https://${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Docker Auth Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.CR_SERVICE }}:latest" -t ${{ env.CR_SERVICE }}:dev .
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.CR_SERVICE }}:dev"

  deploy:
    needs: build
    steps:
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy \${{ env.CR_SERVICE }} \
            --quiet \
            --description "Cloud Run deployment from GitHub Actions, for IP & Location service" \
            --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.CR_SERVICE }}:dev \
                      --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }} \
            --max-instances 2 \
            --port 80 \
            --execution-environment gen2 \
            --allow-unauthenticated